### ISSUE TITLE
Add {{Template}} links

### ISSUE THREAD

**Issue by YacineBoussoufa** [jhsoby/telegram-wikilinksbot#10]
If someone writes {{**WORD**|TEXT}} the bot should link to https://_XXX_.wikipedia.org/wiki/Template:**WORD**/ to simplify using "{" and "}" instead of [[Tempate:....]] or [[t:....]].

**Comment by jhsoby** [comment]
Thanks for the suggestion @YacineBoussoufa!

I am initially a little bit skeptical about adding this – I have thought about it already, but the issue is that almost all instances I see of people using {{this}} syntax in chats is in a semi-joking manner. E.g. by replying to something with {{done}} to indicate that they have fulfilled a request/question, or {{welcome}} or something – they very rarely intend to actually link to the template that is mentioned.

Do you often find a need for this usecase?

**Comment by YacineBoussoufa** [comment]
Often it happens to use it, but I do not think it is used in many groups, it could be a feature that can be activated with a command.

**Comment by jhsoby** [comment]
@nicolasmaia Hi! I'm not sure I did this duplicate issue thing right, I've never done that on GitHub before.

You can see my answer to @YacineBoussoufa above – is {{this}} syntax something you would often use/do you see people use it often (meaning to link to a template)?

**Comment by nicolasmaia** [comment]
Sorry about that, Jon! I hadn't seen this report.

I think if people notice {{done}} etc actually leads to templates they'll be less likely to use it jokingly and more likely to use it to link to actual templates. Right now it's kind of annoying to have to type [[Template:Foobar]] when I could just type {{foobar}}.

**Comment by YacineBoussoufa** [comment]
Thank you 👍🏻

**Comment by jhsoby** [comment]
No problem! It was an interesting challenge for me. :-)

You'd think {{these}} links are as simple as [[these]] link, but that would be wrong – you need to factor in all the {{NUMBEROFARTICLES}}, {{#parser:functions}} and {{#invoke:modules}} as well as {{subst:ing templates}} as well, plus the fact that you can include pages from other namespaces like {{User:My name/sandbox template}}. So it was a fun exercise! :D
