### ISSUE TITLE
check whether unicode character is an emoji

### ISSUE THREAD

**Issue by camelCaseNick** [jhsoby/telegram-wikilinksbot#5]
https://github.com/jhsoby/telegram-wikilinksbot/blob/7c8832e36082f10746d25b4119e5a5d41fdef647/wikilinksbot.py#L73 ff. is also fulfilled by Q174565 with _Q174565 ( brackets_ as the message.

The python package https://pypi.org/project/emoji/ would have the list UNICODE_EMOJI. (It looks like it's the complete list. I have not tested though whether it is indeed the same as https://unicode.org/emoji/charts/full-emoji-list.html and whether modifier characters are in that list.)

The alternative approach would of course be to define this as expected behavior.

**Comment by jhsoby** [comment]
Thanks for the idea!

Since this is just meant as a small easter egg, I would prefer not importing another package to check it, so as to minimize the number of "moving parts", so to speak. I think I will just use a regex to exclude it if the character is part of ASCII, or matches regex' `\w`, which will exclude some Chinese characters used in e.g. Q629.
